apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actorstateservice
  namespace: rollerservices
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value:  
  - name: redisPassword
    value:  
  - name: enableTLS
    value: true # Optional. Allowed: true, false.
  - name: actorStateStore
    value: "true"
